// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: proto/transformer/transformer.proto

package transformer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransformNumberRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int64 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *TransformNumberRequest) Reset() {
	*x = TransformNumberRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_transformer_transformer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransformNumberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformNumberRequest) ProtoMessage() {}

func (x *TransformNumberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transformer_transformer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformNumberRequest.ProtoReflect.Descriptor instead.
func (*TransformNumberRequest) Descriptor() ([]byte, []int) {
	return file_proto_transformer_transformer_proto_rawDescGZIP(), []int{0}
}

func (x *TransformNumberRequest) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

type TransformNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result  int64  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TransformNumberResponse) Reset() {
	*x = TransformNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_transformer_transformer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransformNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransformNumberResponse) ProtoMessage() {}

func (x *TransformNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transformer_transformer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransformNumberResponse.ProtoReflect.Descriptor instead.
func (*TransformNumberResponse) Descriptor() ([]byte, []int) {
	return file_proto_transformer_transformer_proto_rawDescGZIP(), []int{1}
}

func (x *TransformNumberResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

func (x *TransformNumberResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_transformer_transformer_proto protoreflect.FileDescriptor

var file_proto_transformer_transformer_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x65, 0x72, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d,
	0x65, 0x72, 0x22, 0x30, 0x0a, 0x16, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x22, 0x4b, 0x0a, 0x17, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72,
	0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x74, 0x0a, 0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x6f, 0x72, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x23, 0x2e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f,
	0x72, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x24, 0x2e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x2e, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x51, 0x5a, 0x4f, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x68, 0x74, 0x31, 0x30, 0x32, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2d, 0x70, 0x6c, 0x61, 0x79, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2d, 0x6d, 0x65, 0x73, 0x68, 0x2d, 0x6c, 0x6f, 0x61, 0x64, 0x2d, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x66, 0x6f, 0x72, 0x6d, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_transformer_transformer_proto_rawDescOnce sync.Once
	file_proto_transformer_transformer_proto_rawDescData = file_proto_transformer_transformer_proto_rawDesc
)

func file_proto_transformer_transformer_proto_rawDescGZIP() []byte {
	file_proto_transformer_transformer_proto_rawDescOnce.Do(func() {
		file_proto_transformer_transformer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_transformer_transformer_proto_rawDescData)
	})
	return file_proto_transformer_transformer_proto_rawDescData
}

var file_proto_transformer_transformer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_transformer_transformer_proto_goTypes = []interface{}{
	(*TransformNumberRequest)(nil),  // 0: transformer.TransformNumberRequest
	(*TransformNumberResponse)(nil), // 1: transformer.TransformNumberResponse
}
var file_proto_transformer_transformer_proto_depIdxs = []int32{
	0, // 0: transformer.TransformerService.TransformNumber:input_type -> transformer.TransformNumberRequest
	1, // 1: transformer.TransformerService.TransformNumber:output_type -> transformer.TransformNumberResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_transformer_transformer_proto_init() }
func file_proto_transformer_transformer_proto_init() {
	if File_proto_transformer_transformer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_transformer_transformer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransformNumberRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_transformer_transformer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransformNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_transformer_transformer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transformer_transformer_proto_goTypes,
		DependencyIndexes: file_proto_transformer_transformer_proto_depIdxs,
		MessageInfos:      file_proto_transformer_transformer_proto_msgTypes,
	}.Build()
	File_proto_transformer_transformer_proto = out.File
	file_proto_transformer_transformer_proto_rawDesc = nil
	file_proto_transformer_transformer_proto_goTypes = nil
	file_proto_transformer_transformer_proto_depIdxs = nil
}
