// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: proto/subtractor/subtractor.proto

package subtractor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubtractorServiceClient is the client API for SubtractorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubtractorServiceClient interface {
	SubtractNumbers(ctx context.Context, in *SubtractNumbersRequest, opts ...grpc.CallOption) (*SubtractNumbersResponse, error)
}

type subtractorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubtractorServiceClient(cc grpc.ClientConnInterface) SubtractorServiceClient {
	return &subtractorServiceClient{cc}
}

func (c *subtractorServiceClient) SubtractNumbers(ctx context.Context, in *SubtractNumbersRequest, opts ...grpc.CallOption) (*SubtractNumbersResponse, error) {
	out := new(SubtractNumbersResponse)
	err := c.cc.Invoke(ctx, "/subtractor.SubtractorService/SubtractNumbers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubtractorServiceServer is the server API for SubtractorService service.
// All implementations must embed UnimplementedSubtractorServiceServer
// for forward compatibility
type SubtractorServiceServer interface {
	SubtractNumbers(context.Context, *SubtractNumbersRequest) (*SubtractNumbersResponse, error)
	mustEmbedUnimplementedSubtractorServiceServer()
}

// UnimplementedSubtractorServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSubtractorServiceServer struct {
}

func (UnimplementedSubtractorServiceServer) SubtractNumbers(context.Context, *SubtractNumbersRequest) (*SubtractNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubtractNumbers not implemented")
}
func (UnimplementedSubtractorServiceServer) mustEmbedUnimplementedSubtractorServiceServer() {}

// UnsafeSubtractorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubtractorServiceServer will
// result in compilation errors.
type UnsafeSubtractorServiceServer interface {
	mustEmbedUnimplementedSubtractorServiceServer()
}

func RegisterSubtractorServiceServer(s grpc.ServiceRegistrar, srv SubtractorServiceServer) {
	s.RegisterService(&SubtractorService_ServiceDesc, srv)
}

func _SubtractorService_SubtractNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubtractNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtractorServiceServer).SubtractNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subtractor.SubtractorService/SubtractNumbers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtractorServiceServer).SubtractNumbers(ctx, req.(*SubtractNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SubtractorService_ServiceDesc is the grpc.ServiceDesc for SubtractorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubtractorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subtractor.SubtractorService",
	HandlerType: (*SubtractorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubtractNumbers",
			Handler:    _SubtractorService_SubtractNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/subtractor/subtractor.proto",
}
