apiVersion: batch/v1
kind: Job
metadata:
  generateName: transformer-client-
spec:
  ttlSecondsAfterFinished: 180
  template:
    spec:
      containers:
        - name: transformer-client
          image: docker.io/library/transformer-client:1.0.0
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "20m"
          env:
            - name: TRANSFORMER_SERVICE_URL
              value: "transformer-api:8081"
            - name: NUMBER_OF_CALLS
              value: "500"
      restartPolicy: Never
