apiVersion: v1
kind: Service
metadata:
  name: subtractor-api
  labels:
    app: subtractor-api
spec:
  type: ClusterIP
  selector:
    app: subtractor-api
  ports:
    - protocol: TCP
      name: grpc
      port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtractor-api
  labels:
    app: subtractor-api
spec:
  selector:
    matchLabels:
      app: subtractor-api
  replicas: 3
  template:
    metadata:
      labels:
        app: subtractor-api
    spec:
      containers:
        - name: subtractor-api
          image: docker.io/library/subtractor-api:1.0.0
          imagePullPolicy: Never
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "20m"
          ports:
            - containerPort: 8081
          env:
            - name: "GRPC_PORT"
              value: "8081"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
